name: Build and Publish BOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # JDK 21 already in custom runner image - no setup needed!

    - name: Build with Gradle
      run: ./gradlew build --no-daemon --build-cache

    - name: Publish BOM and catalog to Gitea Maven
      if: github.ref == 'refs/heads/main'
      run: ./gradlew publishAllPublicationsToGiteaRepository
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_PAT: ${{ secrets.GIT_PAT }}
