package ai.pipestream.common.util.descriptor;

import com.google.protobuf.DescriptorProtos.FileDescriptorSet;
import com.google.protobuf.Descriptors.DescriptorValidationException;
import com.google.protobuf.Descriptors.FileDescriptor;

import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Loads Protocol Buffer descriptors from Google descriptor set files (.dsc).
 * These files are typically generated by protoc with --descriptor_set_out flag
 * and packaged in JAR files under META-INF/grpc/.
 *
 * <p>Example usage:
 * <pre>
 * GoogleDescriptorLoader loader = new GoogleDescriptorLoader("META-INF/grpc/services.dsc");
 * List&lt;FileDescriptor&gt; descriptors = loader.loadDescriptors();
 * </pre>
 */
public class GoogleDescriptorLoader implements DescriptorLoader {

    private final String descriptorPath;
    private final ClassLoader classLoader;

    /**
     * Default descriptor path used by grpc-google-descriptor module.
     */
    public static final String DEFAULT_DESCRIPTOR_PATH = "META-INF/grpc/services.dsc";

    /**
     * Creates a loader with the default descriptor path.
     */
    public GoogleDescriptorLoader() {
        this(DEFAULT_DESCRIPTOR_PATH);
    }

    /**
     * Creates a loader with a custom descriptor path.
     *
     * @param descriptorPath The classpath resource path to the .dsc file
     */
    public GoogleDescriptorLoader(String descriptorPath) {
        this(descriptorPath, Thread.currentThread().getContextClassLoader());
    }

    /**
     * Creates a loader with a custom descriptor path and class loader.
     *
     * @param descriptorPath The classpath resource path to the .dsc file
     * @param classLoader The class loader to use for loading resources
     */
    public GoogleDescriptorLoader(String descriptorPath, ClassLoader classLoader) {
        this.descriptorPath = descriptorPath;
        this.classLoader = classLoader != null ? classLoader : ClassLoader.getSystemClassLoader();
    }

    @Override
    public List<FileDescriptor> loadDescriptors() throws DescriptorLoadException {
        try (InputStream inputStream = classLoader.getResourceAsStream(descriptorPath)) {
            if (inputStream == null) {
                throw new DescriptorLoadException(
                    "Descriptor file not found on classpath: " + descriptorPath);
            }

            FileDescriptorSet descriptorSet = FileDescriptorSet.parseFrom(inputStream);
            return buildFileDescriptors(descriptorSet);
        } catch (IOException e) {
            throw new DescriptorLoadException(
                "Failed to read descriptor file: " + descriptorPath, e);
        } catch (DescriptorValidationException e) {
            throw new DescriptorLoadException(
                "Invalid descriptor in file: " + descriptorPath, e);
        }
    }

    @Override
    public FileDescriptor loadDescriptor(String fileName) throws DescriptorLoadException {
        List<FileDescriptor> allDescriptors = loadDescriptors();
        return allDescriptors.stream()
            .filter(fd -> fd.getName().equals(fileName))
            .findFirst()
            .orElse(null);
    }

    @Override
    public boolean isAvailable() {
        InputStream stream = classLoader.getResourceAsStream(descriptorPath);
        if (stream != null) {
            try {
                stream.close();
            } catch (IOException e) {
                // Ignore close errors
            }
            return true;
        }
        return false;
    }

    @Override
    public String getLoaderType() {
        return "Google Descriptor File";
    }

    /**
     * Gets the descriptor path being used.
     *
     * @return The descriptor path
     */
    public String getDescriptorPath() {
        return descriptorPath;
    }

    /**
     * Builds FileDescriptors from a FileDescriptorSet, resolving dependencies.
     *
     * @param descriptorSet The descriptor set to build from
     * @return A list of FileDescriptors
     * @throws DescriptorValidationException if descriptor building fails
     */
    private List<FileDescriptor> buildFileDescriptors(FileDescriptorSet descriptorSet)
            throws DescriptorValidationException {

        Map<String, FileDescriptor> descriptorMap = new HashMap<>();
        Map<String, com.google.protobuf.DescriptorProtos.FileDescriptorProto> protoMap = new HashMap<>();

        // First pass: collect all proto descriptors
        for (com.google.protobuf.DescriptorProtos.FileDescriptorProto proto : descriptorSet.getFileList()) {
            protoMap.put(proto.getName(), proto);
        }

        // Second pass: build FileDescriptors with dependency resolution
        for (com.google.protobuf.DescriptorProtos.FileDescriptorProto proto : descriptorSet.getFileList()) {
            if (!descriptorMap.containsKey(proto.getName())) {
                buildFileDescriptor(proto, protoMap, descriptorMap);
            }
        }

        return new ArrayList<>(descriptorMap.values());
    }

    /**
     * Recursively builds a FileDescriptor, resolving its dependencies first.
     *
     * @param proto The FileDescriptorProto to build
     * @param protoMap Map of all available FileDescriptorProtos
     * @param descriptorMap Map to store built FileDescriptors
     * @return The built FileDescriptor
     * @throws DescriptorValidationException if building fails
     */
    private FileDescriptor buildFileDescriptor(
            com.google.protobuf.DescriptorProtos.FileDescriptorProto proto,
            Map<String, com.google.protobuf.DescriptorProtos.FileDescriptorProto> protoMap,
            Map<String, FileDescriptor> descriptorMap) throws DescriptorValidationException {

        // If already built, return it
        if (descriptorMap.containsKey(proto.getName())) {
            return descriptorMap.get(proto.getName());
        }

        // Build dependencies first
        List<FileDescriptor> dependencies = new ArrayList<>();
        for (String dependency : proto.getDependencyList()) {
            FileDescriptor depDescriptor = descriptorMap.get(dependency);
            if (depDescriptor == null) {
                // Try to build the dependency
                com.google.protobuf.DescriptorProtos.FileDescriptorProto depProto = protoMap.get(dependency);
                if (depProto != null) {
                    depDescriptor = buildFileDescriptor(depProto, protoMap, descriptorMap);
                } else {
                    // Dependency not in the descriptor set - might be a well-known type
                    // Try to get it from the runtime
                    depDescriptor = tryGetWellKnownType(dependency);
                    if (depDescriptor == null) {
                        throw new DescriptorValidationException(
                            "Missing dependency: " + dependency + " for " + proto.getName());
                    }
                }
            }
            dependencies.add(depDescriptor);
        }

        // Build this descriptor
        FileDescriptor descriptor = FileDescriptor.buildFrom(
            proto,
            dependencies.toArray(new FileDescriptor[0])
        );

        descriptorMap.put(proto.getName(), descriptor);
        return descriptor;
    }

    /**
     * Tries to get a well-known type descriptor from the protobuf runtime.
     *
     * @param fileName The proto file name
     * @return The FileDescriptor if it's a well-known type, null otherwise
     */
    private FileDescriptor tryGetWellKnownType(String fileName) {
        try {
            // Check common well-known types
            switch (fileName) {
                case "google/protobuf/any.proto":
                    return com.google.protobuf.Any.getDescriptor().getFile();
                case "google/protobuf/struct.proto":
                    return com.google.protobuf.Struct.getDescriptor().getFile();
                case "google/protobuf/timestamp.proto":
                    return com.google.protobuf.Timestamp.getDescriptor().getFile();
                case "google/protobuf/duration.proto":
                    return com.google.protobuf.Duration.getDescriptor().getFile();
                case "google/protobuf/empty.proto":
                    return com.google.protobuf.Empty.getDescriptor().getFile();
                case "google/protobuf/field_mask.proto":
                    return com.google.protobuf.FieldMask.getDescriptor().getFile();
                case "google/protobuf/wrappers.proto":
                    return com.google.protobuf.StringValue.getDescriptor().getFile();
                default:
                    return null;
            }
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Creates a loader that searches for descriptor files in multiple locations.
     *
     * @param paths The paths to search
     * @return A loader that tries each path until one succeeds
     */
    public static GoogleDescriptorLoader searchPaths(String... paths) {
        for (String path : paths) {
            GoogleDescriptorLoader loader = new GoogleDescriptorLoader(path);
            if (loader.isAvailable()) {
                return loader;
            }
        }
        // Return first path as fallback (will fail when loading)
        return new GoogleDescriptorLoader(paths.length > 0 ? paths[0] : DEFAULT_DESCRIPTOR_PATH);
    }
}
